# Generated by Django 3.0.6 on 2020-11-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logindata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=20, null=True)),
                ('lname', models.CharField(blank=True, max_length=20, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=20, null=True)),
                ('mob_no', models.CharField(blank=True, max_length=20, null=True)),
                ('uname', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('info_stat', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'logindata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selectedstud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'selectedstud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20, null=True)),
                ('lname', models.CharField(blank=True, max_length=20, null=True)),
                ('b_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cyear', models.CharField(blank=True, max_length=20, null=True)),
                ('roll', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=900, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=20, null=True)),
                ('mob_no', models.CharField(blank=True, max_length=20, null=True)),
                ('tenth', models.CharField(blank=True, max_length=20, null=True)),
                ('twelth', models.CharField(blank=True, max_length=20, null=True)),
                ('avg_marks', models.CharField(blank=True, max_length=20, null=True)),
                ('nback', models.CharField(blank=True, max_length=20, null=True)),
                ('add_info', models.CharField(blank=True, max_length=900, null=True)),
            ],
            options={
                'db_table': 'studdata',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='admindata',
            options={'managed': False},
        ),
    ]
