# Generated by Django 3.0.6 on 2020-11-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0002_auto_20201125_0808'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admindata',
            table='admindata',
        ),
    ]
