# Generated by Django 3.0.6 on 2020-11-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0003_auto_20201125_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studdata',
            options={'managed': True},
        ),
    ]
