# Generated by Django 3.0.6 on 2020-11-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnpPortal', '0004_auto_20201126_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studdata',
            options={'managed': False},
        ),
    ]
